// DO NOT EDIT. This file was auto-generated by Sqruct.

package mdl

import (
	"github.com/oov/q"
	"github.com/oov/sqruct"
)

// Account represents the following table.
// 	CREATE TABLE "account"(
// 		"id" INTEGER PRIMARY KEY AUTOINCREMENT,
// 		"name" VARCHAR(30) NOT NULL UNIQUE
// 	);
type Account struct {
	ID   int64  `mdl:"pk,notnull,uniq,default,autoincr"`
	Name string `mdl:"notnull,uniq"`
}

func GetAccount(db sqruct.DB, id int64) (*Account, error) {
	b, tbl := zzAccount{}.SelectBuilder()
	sql, args := b.Where(
		q.Eq(tbl.C("id"), id),
	).ToSQL()
	var t Account
	err := db.QueryRow(sql, args...).Scan(zzAccount{}.Pointers(&t))
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *Account) SelectPost(db sqruct.DB) ([]Post, error) {
	b, tbl := zzPost{}.SelectBuilder()
	sql, args := b.Where(
		q.Eq(tbl.C("accountid"), t.ID),
	).ToSQL()
	r, err := db.Query(sql, args...)
	if err != nil {
		return nil, err
	}
	defer r.Close()

	ot := []Post{}
	for r.Next() {
		var e Post
		if err = r.Scan(zzPost{}.Pointers(&e)...); err != nil {
			return nil, err
		}
		ot = append(ot, e)
	}
	if err = r.Err(); err != nil {
		return nil, err
	}
	return ot, nil
}

func (t *Account) Insert(db sqruct.DB) error {

	b, tbl := zzAccount{}.InsertBuilder(t)
	if !sqruct.IsZero(t.ID) {
		sql, args := b.Set(tbl.C("id"), t.ID).ToSQL()
		_, err := db.Exec(sql, args...)
		return err
	}

	sql, args := b.ToSQL()
	r, err := db.Exec(sql, args...)
	if err != nil {
		return err
	}
	var i int64
	if i, err = r.LastInsertId(); err != nil {
		return err
	}

	t.ID = i
	return nil

}

func (t *Account) Update(db sqruct.DB) error {
	b, tbl := zzAccount{}.UpdateBuilder(t)
	sql, args := b.Where(
		q.Eq(tbl.C("id"), t.ID),
	).ToSQL()
	_, err := db.Exec(sql, args...)
	return err
}

func (t *Account) Delete(db sqruct.DB) error {
	b, tbl := zzAccount{}.DeleteBuilder()
	sql, args := b.Where(
		q.Eq(tbl.C("id"), t.ID),
	).ToSQL()
	_, err := db.Exec(sql, args...)
	return err
}

// zzAccount represents Account table schema.
type zzAccount struct{}

func (zzAccount) Columns(b *q.ZSelectBuilder, t q.Table) {
	b.Column(
		t.C("id"),
		t.C("name"),
	)
}

func (zzAccount) Pointers(t *Account) []interface{} {
	return []interface{}{&t.ID, &t.Name}
}

func (zzAccount) InsertBuilder(t *Account) (*q.ZInsertBuilder, q.Table) {
	tbl := q.T("account")
	return q.Insert().Into(tbl).
		Set(tbl.C("name"), t.Name).
		SetDialect(q.SQLite), tbl
}

func (zzAccount) SelectBuilder() (*q.ZSelectBuilder, q.Table) {
	tbl := q.T("account")
	b := q.Select().From(tbl).SetDialect(q.SQLite)
	zzAccount{}.Columns(b, tbl)
	return b, tbl
}

func (zzAccount) UpdateBuilder(t *Account) (*q.ZUpdateBuilder, q.Table) {
	tbl := q.T("account")
	return q.Update(tbl).
		Set(tbl.C("name"), t.Name).
		SetDialect(q.SQLite), tbl
}

func (zzAccount) DeleteBuilder() (*q.ZDeleteBuilder, q.Table) {
	tbl := q.T("account")
	return q.Delete().From(tbl).SetDialect(q.SQLite), tbl
}
