// DO NOT EDIT. This file was auto-generated by Sqruct.

package mdl

import (
	"github.com/jmoiron/sqlx"
	"github.com/oov/sqruct"
)

// Account represents the following table.
// 	CREATE TABLE account(
// 		id INTEGER PRIMARY KEY AUTOINCREMENT,
// 		name VARCHAR(30) NOT NULL UNIQUE
// 	);
type Account struct {
	ID   int64  `mdl:"pk,notnull,uniq,default,autoincr"`
	Name string `mdl:"notnull,uniq"`
}

func GetAccount(e sqlx.Ext, id int64) (*Account, error) {
	var t Account
	err := sqlx.Get(e, &t, e.Rebind("SELECT * FROM account WHERE (id = ?)"), id)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *Account) SelectPost(e sqlx.Ext) ([]Post, error) {
	var ot []Post
	err := sqlx.Select(e, &ot, e.Rebind("SELECT * FROM post WHERE (accountid = ?)"), t.ID)
	if err != nil {
		return nil, err
	}
	return ot, nil
}

func (t *Account) TableName() string {
	return "account"
}

func (t *Account) Columns() []string {
	return []string{"id", "name"}
}

func (t *Account) AutoIncrementColumnIndex() int {
	return 0
}

func (t *Account) Insert(e sqlx.Ext) error {

	useai := sqruct.IsZero(t.ID)
	i, err := sqruct.SQLite{}.Insert(e, t, useai)
	if err != nil {
		return err
	}
	if useai {
		t.ID = i
	}
	return nil

}

func (t *Account) Update(e sqlx.Ext) error {
	_, err := sqlx.NamedExec(e, "UPDATE account SET name = :name WHERE (id = :id)", t)
	return err
}

func (t *Account) Delete(e sqlx.Ext) error {
	_, err := sqlx.NamedExec(e, "DELETE FROM account WHERE (id = :id)", t)
	return err
}
