// DO NOT EDIT. This file was auto-generated by Sqruct.

package mdl

import "github.com/oov/sqruct"

// PostTag represents the following table.
// 	CREATE TABLE posttag(
// 		postid INTEGER NOT NULL,
// 		tagid INTEGER NOT NULL,
// 		FOREIGN KEY (postid) REFERENCES post(id) ON DELETE CASCADE,
// 		FOREIGN KEY (tagid) REFERENCES tag(id) ON DELETE CASCADE,
// 		PRIMARY KEY (postid, tagid)
// 	);
type PostTag struct {
	PostID int64 `mdl:"fk,notnull"`
	TagID  int64 `mdl:"fk,notnull"`
}

func GetPostTag(db sqruct.DB, postid int64, tagid int64) (*PostTag, error) {

	var t PostTag
	err := db.QueryRow(
		"SELECT postid, tagid FROM posttag WHERE (postid = ?)AND(tagid = ?)",
		postid, tagid,
	).Scan(&t.PostID, &t.TagID)
	if err != nil {
		return nil, err
	}
	return &t, nil

}

func (t *PostTag) GetPost(db sqruct.DB) (*Post, error) {

	var ot Post
	err := db.QueryRow(
		"SELECT id, accountid, at, message FROM post WHERE (id = ?)",
		t.PostID,
	).Scan(&ot.ID, &ot.AccountID, &ot.At, &ot.Message)
	if err != nil {
		return nil, err
	}
	return &ot, nil

}

func (t *PostTag) GetTag(db sqruct.DB) (*Tag, error) {

	var ot Tag
	err := db.QueryRow(
		"SELECT id, name FROM tag WHERE (id = ?)",
		t.TagID,
	).Scan(&ot.ID, &ot.Name)
	if err != nil {
		return nil, err
	}
	return &ot, nil

}

func (t *PostTag) TableName() string {
	return "posttag"
}

func (t *PostTag) Columns() []string {
	return []string{"postid", "tagid"}
}

func (t *PostTag) Values() []interface{} {
	return []interface{}{t.PostID, t.TagID}
}

func (t *PostTag) AutoIncrementColumnIndex() int {
	return -1
}

func (t *PostTag) Insert(db sqruct.DB) error {

	_, err := sqruct.SQLite.Insert(db, t.TableName(), t.Columns(), t.Values(), t.AutoIncrementColumnIndex())
	return err

}

func (t *PostTag) Update(db sqruct.DB) error {
	// PostTag has primary key only
	return nil
}

func (t *PostTag) Delete(db sqruct.DB) error {

	_, err := db.Exec(
		"DELETE FROM posttag WHERE (postid = ?)AND(tagid = ?)",
		t.PostID, t.TagID,
	)
	return err

}
