// DO NOT EDIT. This file was auto-generated by Sqruct.

package mdl

import (
	"time"

	"github.com/jmoiron/sqlx"
	"github.com/oov/sqruct"
)

// Post represents the following table.
// 	CREATE TABLE post(
// 		id INTEGER PRIMARY KEY,
// 		accountid INTEGER NOT NULL,
// 		at DATETIME NOT NULL,
// 		message VARCHAR(8125) NOT NULL,
// 		FOREIGN KEY (accountid) REFERENCES account(id) ON DELETE CASCADE
// 	);
type Post struct {
	ID        int64     `mdl:"pk,notnull,uniq,default,autoincr"`
	AccountID int64     `mdl:"fk,notnull"`
	At        time.Time `mdl:"notnull"`
	Message   string    `mdl:"notnull"`
}

func GetPost(e sqlx.Ext, id int64) (*Post, error) {
	var t Post
	err := sqlx.Get(e, &t, e.Rebind("SELECT * FROM post WHERE (id = ?)"), id)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *Post) GetAccount(e sqlx.Ext) (*Account, error) {
	var ot Account
	err := sqlx.Get(e, &ot, e.Rebind("SELECT * FROM account WHERE (id = ?)"), t.AccountID)
	if err != nil {
		return nil, err
	}
	return &ot, nil
}

func (t *Post) SelectPostTag(e sqlx.Ext) ([]PostTag, error) {
	var ot []PostTag
	err := sqlx.Select(e, &ot, e.Rebind("SELECT * FROM posttag WHERE (postid = ?)"), t.ID)
	if err != nil {
		return nil, err
	}
	return ot, nil
}

func (t *Post) TableName() string {
	return "post"
}

func (t *Post) Columns() []string {
	return []string{"id", "accountid", "at", "message"}
}

func (t *Post) AutoIncrementColumnIndex() int {
	return 0
}

func (t *Post) Insert(e sqlx.Ext) error {

	useai := sqruct.IsZero(t.ID)
	i, err := sqruct.SQLite{}.Insert(e, t, useai)
	if err != nil {
		return err
	}
	if useai {
		t.ID = i
	}
	return nil

}

func (t *Post) Update(e sqlx.Ext) error {
	_, err := sqlx.NamedExec(e, "UPDATE post SET accountid = :accountid, at = :at, message = :message WHERE (id = :id)", t)
	return err
}

func (t *Post) Delete(e sqlx.Ext) error {
	_, err := sqlx.NamedExec(e, "DELETE FROM post WHERE (id = :id)", t)
	return err
}
