// DO NOT EDIT. This file was auto-generated by Sqruct.

package mdl

import (
	"github.com/jmoiron/sqlx"
	"github.com/oov/sqruct"
)

// User represents the following table.
// 	CREATE TABLE user(
// 		id INTEGER PRIMARY KEY AUTOINCREMENT,
// 		name VARCHAR(30) NOT NULL UNIQUE
// 	);
type User struct {
	ID   int64  `mdl:"pk,notnull,uniq,default,autoincr"`
	Name string `mdl:"notnull,uniq"`
}

func GetUser(e sqlx.Ext, id int64) (*User, error) {
	var t User
	err := sqlx.Get(e, &t, e.Rebind("SELECT * FROM user WHERE (id = ?)"), id)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func (t *User) SelectPost(e sqlx.Ext) ([]Post, error) {
	var ot []Post
	err := sqlx.Select(e, &ot, e.Rebind("SELECT * FROM post WHERE (userid = ?)"), t.ID)
	if err != nil {
		return nil, err
	}
	return ot, nil
}

func (t *User) Insert(e sqlx.Ext) error {
	z := sqruct.IsZero(t.ID)
	r, err := sqlx.NamedExec(e, sqruct.BuildInsertQuery(
		"user",
		[]string{"id", "name"},
		[]bool{!z, true},
	), t)
	if err != nil {
		return err
	}
	if z {
		t.ID, err = r.LastInsertId()
		return err
	}
	return nil
}

func (t *User) Update(e sqlx.Ext) error {
	_, err := sqlx.NamedExec(e, "UPDATE user SET name = :name WHERE (id = :id)", t)
	return err
}

func (t *User) Delete(e sqlx.Ext) error {
	_, err := sqlx.NamedExec(e, "DELETE FROM user WHERE (id = :id)", t)
	return err
}
